source 'https://rubygems.org'

gem "bundler", "~> 1.13"
gem "rake", "~> 10.0"
gem "rspec", "~> 3.0"
gem "watir", "~> 6.0"
gem "webdrivers", "~> 3.0"
gem "watir_drops", "~> 0.7"
gem 'watir_model', "~> 0.5.4"
gem "data_magic"
gem "require_all"
gem "sauce_whisk"
gem "ui2api"
gem "watigiri"
gem "minitest", "< 5.11"
